[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
  for = "/*"
  [headers.values]
    # Allow images and iframes from Google Drive/Googleusercontent. Adjust if you add stricter origins.
    # Allow Google Fonts and Firebase Identity Toolkit (auth) requests.
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://drive.google.com https://*.googleusercontent.com; media-src 'self' https://drive.google.com https://*.googleusercontent.com; frame-src https://drive.google.com; script-src 'self' https://www.gstatic.com https://www.googletagmanager.com https://apis.google.com https://*.firebaseio.com https://pixel-punk-default-rtdb.firebaseio.com; script-src-elem 'self' https://www.gstatic.com https://www.googletagmanager.com https://apis.google.com https://*.firebaseio.com https://pixel-punk-default-rtdb.firebaseio.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://identitytoolkit.googleapis.com https://www.googleapis.com https://api.telegram.org https://*.firebaseio.com wss://*.firebaseio.com https://*.googleapis.com https://firebasestorage.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; base-uri 'self'; form-action 'self'"



