[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
  for = "/*"
  [headers.values]
    # Allow images and iframes from Google Drive/Googleusercontent. Adjust if you add stricter origins.
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://drive.google.com https://*.googleusercontent.com; media-src 'self' https://drive.google.com https://*.googleusercontent.com; frame-src https://drive.google.com; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; font-src 'self' data:; base-uri 'self'; form-action 'self'"



